### ISSUE TITLE
Feature Request:  List approved packages and functions in yaml file

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/logrx#199]
### Feature Idea

I really like the feature of logging use of Unapproved Packages and Functions. Rather than creating a list within R and saving it as a `.rds` file, though, I'd like to store this information in something like a yaml file, e.g.

```yaml
base: "all"
dplyr: ["mutate", "filter", "summarize"]
ggplot2: "all"
```

Then you could have the option point to that yaml file instead. The existing functionality could stay as is. This would just be another option of specifying the same information.
